CREATE DATABASE QUANLYQUANCAFE
GO
USE QUANLYQUANCAFE
GO

CREATE TABLE NHANVIEN (
MANV uniqueidentifier PRIMARY KEY,
TEN nvarchar(15),
HO nvarchar(50),
SOCMND varchar(15),
DIACHI nvarchar(255),
SDT varchar(15),
NGAYVAOLAM date,
LUONG int,
MATKHAU varchar(255),
LOAINV nvarchar(20),
);

CREATE TABLE NGUYENLIEU (
MANGUYENLIEU	uniqueidentifier PRIMARY KEY,
TEN	nvarchar(50),
DVT	nvarchar(20),
SOLUONG	int,
SOLUONGTOITHIEU	int,
THOIGIANBAOQUAN	int,
TINHTRANG	nvarchar(20),
GHICHU	nvarchar(255),
);

CREATE TABLE THUCUONG (
MATHUCUONG	uniqueidentifier PRIMARY KEY,
TEN	nvarchar(100),
GIA	int,
GHICHU	nvarchar(255),
);

CREATE TABLE PHIEUNHAPNGUYENLIEU (
MAPNNL	uniqueidentifier PRIMARY KEY,
MANV	uniqueidentifier FOREIGN KEY REFERENCES NHANVIEN(MANV),
NGAYNHAP	date,
LINKANH	varchar(255),
);


CREATE TABLE CHITIETPHIEUNHAP (
MACTPNNL	uniqueidentifier PRIMARY KEY,
MAPNNL	uniqueidentifier FOREIGN KEY REFERENCES PHIEUNHAPNGUYENLIEU(MAPNNL),
MANGUYENLIEU	uniqueidentifier,
SOLUONG	int,
);

CREATE TABLE CHITIETTHUCUONG (
MACTTU	uniqueidentifier PRIMARY KEY,
MATHUCUONG	uniqueidentifier FOREIGN KEY REFERENCES THUCUONG(MATHUCUONG),
MANGUYENLIEU	uniqueidentifier FOREIGN KEY REFERENCES NGUYENLIEU(MANGUYENLIEU),
SOLUONG	int,
);

CREATE TABLE HOADON (
MAHOADON	uniqueidentifier PRIMARY KEY,
MANV	uniqueidentifier FOREIGN KEY REFERENCES NHANVIEN(MANV),
NGAYLAP	date,
TONGTIEN	bigint,
DAXOA	bit,
);

CREATE TABLE CHITIETHOADON (
MACTHD	uniqueidentifier PRIMARY KEY,
MAHOADON	uniqueidentifier FOREIGN KEY REFERENCES HOADON(MAHOADON),
MATHUCUONG	uniqueidentifier FOREIGN KEY REFERENCES THUCUONG(MATHUCUONG),
SOLUONG	int,
);

--CREATE TABLE CHITIETPHACHE (
--MACTPC	uniqueidentifier PRIMARY KEY,
--MACTHD	uniqueidentifier FOREIGN KEY REFERENCES CHITIETHOADON(MACTHD),
--MANGUYENLIEU	uniqueidentifier,
--SOLUONG	int,
--);

CREATE TABLE BAOCAO (
MABAOCAO	uniqueidentifier PRIMARY KEY,
MANV	uniqueidentifier FOREIGN KEY REFERENCES NHANVIEN(MANV),
LOAI	nvarchar(40),
LINKFILE	nvarchar(255),
);
GO

ALTER TABLE NHANVIEN
ADD CONSTRAINT DF_MANV DEFAULT NEWID() FOR MANV;
ALTER TABLE NGUYENLIEU
ADD CONSTRAINT DF_MANGUYENLIEU DEFAULT NEWID() FOR MANGUYENLIEU;
ALTER TABLE THUCUONG
ADD CONSTRAINT DF_MATHUCUONG DEFAULT NEWID() FOR MATHUCUONG;
ALTER TABLE PHIEUNHAPNGUYENLIEU
ADD CONSTRAINT DF_MAPNNL DEFAULT NEWID() FOR MAPNNL;
--ALTER TABLE PHIEUCAPNHATNGUYENLIEU
--ADD CONSTRAINT DF_MAPCNNL DEFAULT NEWID() FOR MAPCNNL;
ALTER TABLE CHITIETPHIEUNHAP
ADD CONSTRAINT DF_MACTPNNL DEFAULT NEWID() FOR MACTPNNL;
--ALTER TABLE CHITIETPHIEUCAPNHAT
--ADD CONSTRAINT DF_MACTPCNNL DEFAULT NEWID() FOR MACTPCNNL;
ALTER TABLE CHITIETTHUCUONG
ADD CONSTRAINT DF_MACTTU DEFAULT NEWID() FOR MACTTU;
ALTER TABLE HOADON
ADD CONSTRAINT DF_MAHOADON DEFAULT NEWID() FOR MAHOADON;
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT DF_MACTHD DEFAULT NEWID() FOR MACTHD;
--ALTER TABLE CHITIETPHACHE
--ADD CONSTRAINT DF_MACTPC DEFAULT NEWID() FOR MACTPC;
ALTER TABLE BAOCAO
ADD CONSTRAINT DF_MABAOCAO DEFAULT NEWID() FOR MABAOCAO;
GO

ALTER TABLE CHITIETPHIEUNHAP
ADD CONSTRAINT FK_MANGUYENLIEU FOREIGN KEY (MANGUYENLIEU) REFERENCES NGUYENLIEU(MANGUYENLIEU);

ALTER TABLE NHANVIEN
ALTER COLUMN SDT varchar(15) NOT NULL

ALTER TABLE NHANVIEN ADD CONSTRAINT U_SDT UNIQUE(SDT)
GO

CREATE PROC NHANVIEN_SELECTALL
AS
	SELECT [MANV]
      ,[TEN]
      ,[HO]
      ,[SOCMND]
      ,[DIACHI]
      ,[SDT]
      ,[NGAYVAOLAM]
      ,[LUONG]
      ,[LOAINV]
  FROM [dbo].[NHANVIEN]
GO

CREATE PROC NHANVIEN_SELECTBYCMND(@SoCMND varchar(15))
AS
	SELECT [MANV]
	   ,[TEN]
	   ,[HO]
	   ,[SOCMND]
	   ,[DIACHI]
	   ,[SDT]
	   ,[NGAYVAOLAM]
	   ,[LUONG]
	   ,[LOAINV]
  FROM [dbo].[NHANVIEN] WHERE SOCMND = @SoCMND
GO

CREATE PROC NHANVIEN_SELECT(@Sdt varchar(15),@MatKhau varchar(255))
AS
	SELECT * FROM NHANVIEN WHERE SDT = @Sdt AND MATKHAU = @MatKhau
GO

CREATE PROC NHANVIEN_INSERT(@Ten nvarchar(15),@Ho nvarchar(50), @SoCMND varchar(15), @DiaChi nvarchar(255),@Sdt varchar(15), @NgayVaoLam date, @Luong int, @MatKhau varchar(255), @LoaiNV nvarchar(20))
AS
	INSERT INTO NHANVIEN(TEN,HO,SOCMND,DIACHI,SDT,NGAYVAOLAM,LUONG,MATKHAU,LOAINV)
	VALUES (@Ten,@Ho,@SoCMND,@DiaChi,@Sdt,@NgayVaoLam,@Luong,@MatKhau,@LoaiNV)
GO

CREATE PROC NHANVIEN_UPDATE(@MaNV uniqueidentifier, @Ten nvarchar(15),@Ho nvarchar(50), @SoCMND varchar(15), @DiaChi nvarchar(255),@Sdt varchar(15), @NgayVaoLam date, @Luong int, @MatKhau varchar(255), @LoaiNV nvarchar(20))
AS
	UPDATE NHANVIEN
	SET TEN = @Ten,
	HO = @Ho,
	SOCMND = @SoCMND,
	DIACHI = @DiaChi,
	SDT = @Sdt,
	NGAYVAOLAM = @NgayVaoLam,
	LUONG = @Luong,
	MATKHAU = @MatKhau,
	LOAINV = @LoaiNV
	WHERE MANV = @MaNV
GO

CREATE PROC NHANVIEN_DELETE (@MaNV uniqueidentifier)
AS
	DELETE FROM NHANVIEN
	WHERE MANV = @MaNV
GO

CREATE PROC CHITIETPHIEUNHAP_INSERT(@MaPNNL uniqueidentifier, @MaNL uniqueidentifier, @SoLuong int)
AS
	INSERT INTO CHITIETPHIEUNHAP(MAPNNL,MANGUYENLIEU,SOLUONG)
	VALUES (@MaPNNL,@MaNL,@SoLuong)
GO

CREATE PROC PHIEUNHAPNGUYENLIEU_INSERT(@MaNV uniqueidentifier, @NgayNhap date, @LinkAnh varchar(255))
AS
	INSERT INTO PHIEUNHAPNGUYENLIEU(MANV,NGAYNHAP,LINKANH) OUTPUT inserted.MAPNNL
	VALUES (@MaNV,@NgayNhap,@LinkAnh)
GO


CREATE PROC NGUYENLIEU_INSERT(@Ten nvarchar(50),@Dvt nvarchar(20), @SoLuong int, @SoLuongToiThieu int, @ThoiGianBaoQuan int, @GhiChu nvarchar(255))
AS
	INSERT INTO NGUYENLIEU(TEN,DVT,SOLUONG,SOLUONGTOITHIEU,THOIGIANBAOQUAN,GHICHU)
	VALUES (@Ten,@Dvt,@SoLuong,@SoLuongToiThieu,@ThoiGianBaoQuan,@GhiChu)
GO

CREATE PROC NGUYENLIEU_UPDATE(@MaNguyenLieu uniqueidentifier, @Ten nvarchar(50),@Dvt nvarchar(20), @SoLuong int, @SoLuongToiThieu int, @ThoiGianBaoQuan int, @GhiChu nvarchar(255))
AS
	UPDATE NGUYENLIEU
	SET TEN = @Ten,
	DVT = @Dvt,
	SOLUONG = @SoLuong,
	SOLUONGTOITHIEU = @SoLuongToiThieu,
	THOIGIANBAOQUAN = @ThoiGianBaoQuan,
	GHICHU = @GhiChu
	WHERE MANGUYENLIEU = @MaNguyenLieu
GO

CREATE PROC NGUYENLIEU_SELECTALL
AS
	SELECT * FROM NGUYENLIEU
GO

CREATE PROC NGUYENLIEU_SELECTBYNAME(@Ten nvarchar(50))
AS
	SELECT * FROM NGUYENLIEU WHERE TEN = @Ten
GO

CREATE PROC NGUYENLIEU_SELECTBAD
AS
	SELECT * FROM NGUYENLIEU nl
	WHERE SOLUONG < SOLUONGTOITHIEU OR DATEDIFF(DAY,(SELECT TOP 1 NGAYNHAP FROM PHIEUNHAPNGUYENLIEU,CHITIETPHIEUNHAP,NGUYENLIEU nl2
	WHERE nl.MANGUYENLIEU = nl2.MANGUYENLIEU AND nl2.MANGUYENLIEU = CHITIETPHIEUNHAP.MANGUYENLIEU AND CHITIETPHIEUNHAP.MAPNNL = PHIEUNHAPNGUYENLIEU.MAPNNL),GETDATE()) > THOIGIANBAOQUAN OR
	nl.MANGUYENLIEU NOT IN (SELECT cttu.MANGUYENLIEU FROM CHITIETTHUCUONG cttu)
GO

CREATE PROC NGUYENLIEU_SELECTNEEDTOIMPORT
AS
	SELECT * FROM NGUYENLIEU
	WHERE SOLUONG < SOLUONGTOITHIEU
GO

CREATE PROC THUCUONG_SELECTALL
AS
	SELECT* FROM THUCUONG
GO

CREATE PROC THUCUONG_SELECTBYNAME(@Ten nvarchar(100))
AS
	SELECT * FROM THUCUONG
	WHERE TEN = @Ten
GO


CREATE PROC THUCUONG_INSERT(@Ten nvarchar(100),@Gia int,@GhiChu nvarchar(255))
AS
	INSERT INTO THUCUONG(TEN,GIA,GHICHU) OUTPUT inserted.MATHUCUONG
	VALUES (@Ten,@Gia,@GhiChu)
GO

CREATE PROC CHITIETTHUCUONG_INSERT(@MaTU uniqueidentifier, @MaNL uniqueidentifier, @SoLuong int)
AS
	INSERT INTO CHITIETTHUCUONG(MATHUCUONG,MANGUYENLIEU,SOLUONG)
	VALUES (@MaTU,@MaNL,@SoLuong)
GO

CREATE PROC CHITIETTHUCUONG_SELECTBYMANL(@MaNL uniqueidentifier)
AS
	SELECT * FROM CHITIETTHUCUONG WHERE MANGUYENLIEU = @MaNL
GO

CREATE PROC CHITIETTHUCUONG_SELECTBYMATU(@MaTU uniqueidentifier)
AS
	SELECT * FROM CHITIETTHUCUONG WHERE MATHUCUONG = @MaTU
GO


CREATE PROC CHITIETTHUCUONG_DELETE(@MaCTTU uniqueidentifier)
AS
	SELECT * FROM CHITIETTHUCUONG WHERE MACTTU = @MaCTTU
GO

CREATE PROC THUCUONG_DELETE(@MaTU uniqueidentifier)
AS
	DELETE FROM THUCUONG WHERE MATHUCUONG = @MaTU
GO

CREATE PROC THUCUONG_UPDATE(@MaTU uniqueidentifier, @Ten nvarchar(100), @Gia int, @GhiChu nvarchar(255))
AS
	UPDATE THUCUONG
	SET TEN = @Ten,
	GIA = @Gia,
	GHICHU = @GhiChu
	WHERE MATHUCUONG = @MaTU
GO

CREATE PROC CHITIETTHUCUONG_UPDATE(@MaCTTU uniqueidentifier, @MaTU uniqueidentifier, @MaNL uniqueidentifier, @SoLuong int)
AS
	UPDATE CHITIETTHUCUONG
	SET MATHUCUONG = @MaTU,
	MANGUYENLIEU = @MaNL,
	SOLUONG = @SoLuong
	WHERE MACTTU = @MaCTTU
GO

ALTER TABLE HOADON
ADD CONSTRAINT DF_DAXOA DEFAULT(0) FOR DAXOA
GO

CREATE PROC HOADON_INSERT(@MaNV uniqueidentifier, @NgayLap DateTime, @TongTien bigint)
AS
	INSERT INTO HOADON(MANV,NGAYLAP,TONGTIEN,DAXOA) OUTPUT inserted.MAHOADON
	VALUES (@MaNV,@NgayLap,@TongTien,0)
GO

CREATE PROC CHITIETHOADON_INSERT(@MaHoaDon uniqueidentifier, @MaTU uniqueidentifier, @SoLuong int)
AS
	INSERT INTO CHITIETHOADON(MAHOADON,MATHUCUONG,SOLUONG)
	VALUES (@MaHoaDon,@MaTU,@SoLuong)
GO

--CREATE PROC CHITIETPHACHE_INSERT(@MaCTHD uniqueidentifier, @MaNL uniqueidentifier, @SoLuong int)
--AS
--	INSERT INTO CHITIETPHACHE(MACTHD,MANGUYENLIEU,SOLUONG)
--	VALUES (@MaCTHD,@MaNL,@SoLuong)
--GO

CREATE PROC HOADON_DELETE(@MaHoaDon uniqueidentifier)
AS
	UPDATE HOADON
	SET DAXOA = 1
	WHERE MAHOADON = @MaHoaDon
GO

CREATE PROC HOADON_SELECTALL
AS
	SELECT * FROM HOADON
GO

CREATE PROC BAOCAO_INSERT(@MaNV uniqueidentifier, @Loai nvarchar(40), @LinkFile nvarchar(255))
AS
	INSERT INTO BAOCAO(MANV,LOAI,LINKFILE)
	VALUES (@MaNV,@Loai,@LinkFile)
GO

CREATE PROC HOADON_TINHTONGTIEN(@MaHD uniqueidentifier)
AS
	DECLARE @TongTien BIGINT
	SELECT @TongTien = SUM(CHITIETHOADON.SOLUONG*THUCUONG.GIA)
	FROM CHITIETHOADON,THUCUONG
	WHERE CHITIETHOADON.MAHOADON = @MaHD AND THUCUONG.MATHUCUONG = CHITIETHOADON.MATHUCUONG
	UPDATE HOADON SET TONGTIEN = @TongTien WHERE MAHOADON = @MaHD
GO

CREATE PROC NGUYENLIEU_IMPORT(@MaPNNL uniqueidentifier)
AS
	UPDATE NGUYENLIEU
	SET SOLUONG = nl.SOLUONG + ctpn.SOLUONG
	FROM NGUYENLIEU nl, CHITIETPHIEUNHAP ctpn
	WHERE ctpn.MAPNNL = @MaPNNL
	AND ctpn.MANGUYENLIEU = nl.MANGUYENLIEU
GO

CREATE PROC NGUYENLIEU_DELETE(@MaNL uniqueidentifier)
AS
	DELETE FROM NGUYENLIEU WHERE MANGUYENLIEU = @MaNL
GO

INSERT INTO THUCUONG(TEN,GIA,GHICHU) OUTPUT INSERTED.MATHUCUONG VALUES ('ABC',123,'ABC') 

